// lib/moods.ts
export const moods = [
  { mood: "Happy 😊", swedish: "Glad 😊" },
  { mood: "Content 😌", swedish: "Tillfreds 😌" },
  { mood: "Excited 🤩", swedish: "Uppspelt 🤩" },
  { mood: "Calm 🕊️", swedish: "Lugn 🕊️" },
  { mood: "Peaceful 🌿", swedish: "Fridfull 🌿" },
  { mood: "Grateful 🙏", swedish: "Tacksam 🙏" },
  { mood: "Sad 😔", swedish: "Ledsen 😔" },
  { mood: "Down 🫤", swedish: "Nedstämd 🫤" },
  { mood: "Lonely 🫥", swedish: "Ensam 🫥" },
  { mood: "Anxious 😰", swedish: "Orolig 😰" },
  { mood: "Stressed 😵‍💫", swedish: "Stressad 😵‍💫" },
  { mood: "Overwhelmed 🫨", swedish: "Överväldigad 🫨" },
  { mood: "Tired 🥱", swedish: "Trött 🥱" },
  { mood: "Exhausted 😩", swedish: "Utmattad 😩" },
  { mood: "Unmotivated 😶‍🌫️", swedish: "Oinspirerad 😶‍🌫️" },
  { mood: "Angry 😡", swedish: "Arg 😡" },
  { mood: "Frustrated 😤", swedish: "Frustrerad 😤" },
  { mood: "Irritated 😒", swedish: "Irriterad 😒" },
  { mood: "Hopeful 🌅", swedish: "Hoppfull 🌅" },
  { mood: "Motivated 💪", swedish: "Motiverad 💪" },
  { mood: "Inspired ✨", swedish: "Inspirerad ✨" },
  { mood: "Meh 😐", swedish: "Sådär 😐" },
  { mood: "Neutral 😶", swedish: "Neutral 😶" },
  { mood: "Numb 🫥", swedish: "Avstängd 🫥" },
];
